language: rust
sudo: false
rust:
  - 1.31.0 # 2018!
  - 1.32.0 # rand
  - 1.36.0 # alloc
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - ./ci/test_full.sh
matrix:
  include:
    # try a target that doesn't have std at all, but does have alloc
    - name: "alloc"
      rust: stable
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
      script:
        - cargo build --verbose --target $TARGET --no-default-features --features "alloc libm serde rand"
    # try a target that doesn't have std at all, nor alloc
    - name: "no_std"
      rust: 1.31.0
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
      script:
        - cargo build --verbose --target $TARGET --no-default-features --features libm
    - name: "rustfmt"
      rust: 1.31.0
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
notifications:
  email:
    on_success: never
branches:
  only:
    - master
    - next
    - staging
    - trying
