[package]
authors = ["Åukasz Jan Niemier <lukasz@niemier.pl>"]
name = "num-rational"
version = "0.1.0"

[dependencies]

[dependencies.num-bigint]
optional = true
path = "../bigint"

[dependencies.num-integer]
path = "../integer"

[dependencies.num-traits]
path = "../traits"

[dependencies.serde]
optional = true
version = "0.7.0"

[features]
default = ["bigint"]
bigint = ["num-bigint"]
